spring:
  allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${APP_HOSTNAME}:8080/realms/store-manager-realm
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: product-service
          uri: http://product-service:8081
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/products/?(?<segment>.*), /$\{segment}
        - id: inventory-service
          uri: http://inventory-service:8082
          predicates:
            - Path=/inventory/**
          filters:
            - RewritePath=/inventory/?(?<segment>.*), /$\{segment}
        - id: order-service
          uri: http://order-service:8083
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders/?(?<segment>.*), /$\{segment}

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"

server:
  port: 8765
  forward-headers-strategy: framework