  spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: ${DATASOURCE_URL}
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD}
    flyway:
      url: ${DATASOURCE_URL}
      user: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD}