spring:
  allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${APP_HOSTNAME}:8080/realms/store-manager-realm
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: product-service
          uri: http://${APP_HOSTNAME}:8081
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/?(?<segment>.*), /$\{segment}
        - id: inventory-service
          uri: http://${APP_HOSTNAME}:8082
          predicates:
            - Path=/inventory/**
          filters:
            - RewritePath=/inventory/?(?<segment>.*), /$\{segment}
        - id: order-service
          uri: http://${APP_HOSTNAME}:8083
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/?(?<segment>.*), /$\{segment}