version: '3.15'

name: store-manager
services:
  network-bridge:
    container_name: ${APP_HOSTNAME}
    image: alpine:latest
    command: sleep infinity
    ports:
      - "8080:8080"
      - "8761:8761"
      - "8765:8765"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    restart: on-failure
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: ${KC_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_PASSWORD}
    depends_on:
      - network-bridge
    network_mode: "service:network-bridge"

  kafka:
    container_name: kafka
    image: apache/kafka:3.8.0
    restart: on-failure
    network_mode: "service:network-bridge"

  database:
    container_name: ${POSTGRES_HOSTNAME}
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  config-service:
    container_name: config-service
    build: ../config-service
    restart: on-failure
    network_mode: "service:network-bridge"

  db-migration-service:
    container_name: db-migration-service
    build: ../db-migration-service
    restart: on-failure
    environment:
      APP_HOSTNAME: ${APP_HOSTNAME}
      DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOSTNAME}:5432/${POSTGRES_DB}
      DATASOURCE_USERNAME: ${POSTGRES_USER}
      DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - config-service
      - database
    network_mode: "service:network-bridge"

  discovery-service:
    container_name: discovery-service
    build: ../discovery-service
    restart: on-failure
    environment:
      APP_HOSTNAME: ${APP_HOSTNAME}
    depends_on:
      - config-service
    network_mode: "service:network-bridge"

  gateway-service:
    container_name: gateway-service
    build: ../gateway-service
    restart: on-failure
    environment:
      APP_HOSTNAME: ${APP_HOSTNAME}
    depends_on:
      - config-service
      - keycloak
      - product-service
      - inventory-service
      - order-service
    network_mode: "service:network-bridge"

  product-service:
    container_name: product-service
    build: ../product-service
    restart: on-failure
    environment:
      APP_HOSTNAME: ${APP_HOSTNAME}
      DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOSTNAME}:5432/${POSTGRES_DB}
      DATASOURCE_USERNAME: ${POSTGRES_USER}
      DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - config-service
      - discovery-service
      - db-migration-service
    network_mode: "service:network-bridge"

  inventory-service:
    container_name: inventory-service
    build: ../inventory-service
    restart: on-failure
    environment:
      APP_HOSTNAME: ${APP_HOSTNAME}
      DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOSTNAME}:5432/${POSTGRES_DB}
      DATASOURCE_USERNAME: ${POSTGRES_USER}
      DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - config-service
      - discovery-service
      - db-migration-service
      - kafka
    network_mode: "service:network-bridge"

  order-service:
    container_name: order-service
    build: ../order-service
    restart: on-failure
    environment:
      APP_HOSTNAME: ${APP_HOSTNAME}
      DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOSTNAME}:5432/${POSTGRES_DB}
      DATASOURCE_USERNAME: ${POSTGRES_USER}
      DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - config-service
      - discovery-service
      - db-migration-service
      - kafka
    network_mode: "service:network-bridge"